title:              won의 데이터 사이언스 세계
email:              hwk0702@gmail.com
description:        데이터 사이언스
author:             Hyeongwon Kang
baseurl:            "https://hwk0702.github.io"
url:                "https://hwk0702.github.io"

# Social Profiles
twitter_username:
github_username:    hwk0702
facebook_username:
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
  - jekyll-polyglot

languages: ['ja', 'ko', 'en']
default_lang: 'ko'
exclude_from_localization: ['javascript', 'images', 'css']
parallel_localization: false
